export const OBTENER_CLIENTES = 'OBTENER_CLIENTES';
export const AGREGAR_CLIENTE = 'AGREGAR_CLIENTE';
export const FILTRAR_CLIENTES = 'FILTRAR_CLIENTES';
export const MOSTRAR_AGREGAR_CLIENTE = 'MOSTRAR_AGREGAR_CLIENTE';
export const CLIENTE_ACTUAL = 'CLIENTE_ACTUAL';
export const ACTUALIZAR_CLIENTE = 'ACTUALIZAR_CLIENTE';